
import React, { useState, useEffect, createContext, useContext } from 'react';
import { Routes, Route, useLocation } from 'react-router-dom';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import Home from './pages/Home';
import Products from './pages/Products';
import About from './pages/About';
import Services from './pages/Services';
import Contact from './pages/Contact';
import ChatBot from './components/ChatBot';

export type Language = 'en' | 'ar' | 'vi' | 'zh' | 'es' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: 'HOME',
    products: 'PRODUCTS',
    services: 'SERVICES',
    about: 'ABOUT US',
    contact: 'CONTACT US',
    hero_title: 'Your Trusted Import & Export Partner in Vietnam',
    hero_subtitle: "Connecting Vietnam's best natural and manufactured goods with international buyers who value quality, reliability, and long term excellence.",
    explore: 'Explore Our Services',
    learn_more: 'Learn More',
    years_trust: 'Years of Trust',
    about_title: 'About Ideal Deal Vietnam',
    about_heading: 'Bridging Markets with Integrity and Professionalism',
    about_p1: "Based in the heart of Vietnam's booming economy, we specialize in the export of premium Vietnamese products to global markets. Our journey is built on the foundation of trust and meticulous attention to detail.",
    about_p2: "We don't just facilitate transactions; we build partnerships. By connecting Vietnam's most reliable manufacturers with buyers worldwide, we ensure every deal is 'ideal' safe, efficient, and mutually beneficial.",
    quality_first: 'Quality First',
    quality_desc: 'Rigorous inspection standards.',
    global_reach: 'Global Reach',
    global_desc: 'Across 7 continents.',
    footer_desc: 'Your strategic partner for high quality Vietnamese products to the global market. Built on trust, driven by excellence.',
    copyright: 'Copyright © 2025 Ideal Deal Vietnam. All rights reserved.',
    built_on_trust: 'Built On Trust',
    products_title: 'Industries & Products',
    products_desc: "Connecting Vietnam's manufacturing excellence and natural abundance to the global marketplace with unwavering reliability.",
    all_sectors: 'All Sectors',
    agriculture: 'Agriculture',
    manufacturing: 'Manufacturing',
    consumer_goods: 'Consumer Goods',
    our_story: 'Our Story',
    redefining_trade: 'Redefining Global Trade',
    about_hero_desc: 'Ideal Deal Vietnam: Your bridge between premium Vietnamese quality and the international marketplace.',
    about_excellence: 'Built on Trust, Driven by Excellence',
    about_p3: 'Welcome to Ideal Deal Vietnam, your trusted partner in global trade. Based in the heart of Vietnam\'s booming industrial landscape, we specialize in the export of high-quality Vietnamese products to markets across the world.',
    about_p4: 'With a strong commitment to excellence, reliability, and long-term partnerships, we connect Vietnam’s best natural and manufactured goods with international buyers who value quality and consistency above all else.',
    our_foundation: 'Our Foundation',
    mission: 'Our Mission',
    mission_desc: 'To empower Vietnamese producers by providing a seamless gateway to global markets, ensuring every deal is built on a foundation of mutual success and transparency.',
    vision: 'Our Vision',
    vision_desc: 'To become the leading B2B trade facilitator in Southeast Asia, recognized globally for setting the standard in supply chain integrity and operational efficiency.',
    values: 'Our Values',
    value1: 'Transparency in every step',
    value2: 'Uncompromising Efficiency',
    value3: 'Deep-rooted Trust',
    services_hero_title: 'Our Services',
    services_hero_desc: 'Empowering international businesses with seamless Vietnamese market entry, quality-assured sourcing, and end-to-end logistics solutions.',
    sourcing: 'Product Sourcing',
    sourcing_desc: 'Vietnam offers a wealth of high-quality manufactured and natural goods. We bridge the gap by identifying the finest products that meet your specific market demands.',
    supplier_id: 'Supplier Identification',
    supplier_desc: 'Finding the right partner is critical. We vet thousands of local manufacturers to ensure you work with reliable, ethical, and capable suppliers.',
    quality_assurance: 'Quality Assurance',
    qa_desc: 'We act as your eyes and ears on the ground. Our meticulous inspection process ensures that every shipment meets your exact specifications.',
    ready_expand: 'Ready to expand your trade?',
    ready_desc: 'Contact our expert team today to discuss your specific requirements and get a tailored quotation for your business.',
    request_quote: 'REQUEST A QUOTE',
    case_studies: 'VIEW CASE STUDIES',
    discuss_needs: "Let's Discuss Your Sourcing Needs",
    contact_hero_desc: 'Your trusted partner in global trade, bridging the gap between Vietnamese excellence and international demand.',
    send_message: 'Send Us a Message',
    full_name: 'Full Name',
    email: 'Business Email',
    company: 'Company Name',
    message: 'Message',
    send_inquiry: 'SEND INQUIRY',
    contact_info: 'Contact Information',
    office: 'Vietnam Office',
    address: 'District 1, Ho Chi Minh City, Vietnam',
    email_us: 'Email Us',
    call_us: 'Call Us',
    business_hours: 'Business Hours',
    hours: 'Mon - Fri: 8:00 AM - 6:00 PM (GMT+7)',
    view_maps: 'View on Maps',
    success_msg: 'Thank you! Your inquiry has been received. Our team will contact you shortly.',
    bot_welcome: "Hello! I'm Ideal, your trade assistant. How can I help you today?",
    bot_placeholder: "Ask me anything...",
    bot_title: "Ideal Trade Assistant",
    full_spectrum_title: "Full Spectrum Trade Services",
    full_spectrum_desc: "We streamline the entire supply chain process, from the first sample to the final delivery at your doorstep.",
    strategic_sourcing: "Strategic Sourcing",
    strategic_sourcing_desc: "Identifying and vetting the most reliable manufacturers in Vietnam to match your specific product requirements and quality standards.",
    qa_card_title: "Quality Assurance",
    qa_card_desc: "On-site inspections and rigorous testing protocols to ensure that every shipment meets your expectations before leaving the warehouse.",
    logistics_mgmt: "Logistics Management",
    logistics_mgmt_desc: "Handling complex customs documentation and coordinating freight to ensure timely and cost-effective delivery worldwide.",
    ideal_choice_title: "The Ideal Choice for B2B International Trade",
    unmatched_network: "Unmatched Local Network",
    unmatched_network_desc: "Direct access to top tier Vietnamese manufacturers and raw material suppliers.",
    total_transparency: "Total Transparency",
    total_transparency_desc: "Real-time tracking and clear, honest communication at every stage of the deal.",
    risk_mitigation: "Risk Mitigation",
    risk_mitigation_desc: "We handle the legalities and standards compliance so you can focus on growing your business.",
    discuss_next_deal: "Let's Discuss Your Next Global Deal",
    discuss_next_deal_desc: "Whether you're seeking reliable suppliers, business collaborations, or product information, our team is ready to assist with professionalism and efficiency.",
    subject: "Subject",
    trust_integrity_title: "Our Commitment",
    trust_integrity_quote: "Transparency and trust are not just words for us; they are the pillars upon which every successful partnership is built.",
    invalid_email: "Please enter a valid email address.",
    faq_title: "Frequently Asked Questions",
    faq_subtitle: "Find answers to common questions about our import/export solutions.",
    q1: "How do you ensure product quality?",
    a1: "We conduct multi-stage on-site inspections, factory audits, and pre-shipment checks to ensure every product meets international standards and your specific requirements.",
    q2: "What is the typical minimum order quantity (MOQ)?",
    a2: "MOQs vary by industry and manufacturer. However, our strong supplier network allows us to negotiate flexible terms, often facilitating smaller initial orders for new international partners.",
    q3: "Do you handle all logistics and customs?",
    a3: "Yes, we provide end-to-end logistics management. This includes documentation, freight coordination, and customs clearance support to ensure a seamless delivery to your destination.",
    q4: "Can you source products not listed in your catalog?",
    a4: "Absolutely. Our extensive local network allows us to source virtually any high-quality Vietnamese product. Just provide us with your specifications, and we'll find the ideal supplier.",
    q5: "What are your standard payment terms?",
    a5: "We typically work with T/T (Telegraphic Transfer) or L/C (Letter of Credit) at sight. Specific terms can be negotiated based on order volume and partnership history.",
    q6: "How long does the sourcing process typically take?",
    a6: "Initial supplier identification usually takes 5-7 business days. Full production cycles depend on the product type and quantity, but we always aim for maximum efficiency.",
    q7: "Do you offer OEM and Private Label services?",
    a7: "Yes, we specialize in helping brands manufacture their own products in Vietnam, providing full support from design compliance to final packaging.",
    track_shipment: 'Track Your Shipment',
    tracking_placeholder: 'Enter tracking number (e.g., IDV12345)',
    track_now: 'TRACK NOW',
    shipment_not_found: 'Shipment not found. Please check the number.',
    status_label: 'Current Status',
    location_label: 'Last Location',
    status_in_transit: 'In Transit',
    status_delivered: 'Delivered',
    status_processing: 'Processing at Warehouse',
    status_pending: 'Pending Pickup',
    inquiry_type: 'Inquiry Type',
    general_inquiry: 'General Inquiry',
    prod_sourcing: 'Product Sourcing',
    partnership: 'Partnership',
    support: 'Support',
    bot_error: 'Something went wrong. Please try again.',
    try_again: 'Try Again',
    bot_error_quota: "We're receiving too many requests. Please wait a few seconds.",
    bot_error_offline: "You appear to be offline. Please check your connection.",
    bot_suggestion_contact: "Contact Support",
    ai_recommended: 'AI-Powered Recommendations',
    ai_insight: 'AI Insight',
    ai_analyzing: 'Analyzing your trading preferences...',
    ai_no_data: 'Start exploring categories to get personalized product recommendations.',
    team_title: 'Our Leadership Team',
    team_subtitle: 'Meet the experts bridging Vietnamese quality with global markets.',
    ceo_role: 'Founder & CEO',
    sourcing_role: 'Head of Global Sourcing',
    logistics_role: 'Director of Logistics',
    qa_role: 'QA & Compliance Manager'
  },
  fr: {
    home: 'ACCUEIL',
    products: 'PRODUITS',
    services: 'SERVICES',
    about: 'À PROPOS',
    contact: 'CONTACTEZ-NOUS',
    hero_title: "Votre Partenaire d'Import-Export de Confiance au Vietnam",
    hero_subtitle: "Connecter les meilleurs produits naturels et manufacturés du Vietnam avec des acheteurs internationaux qui apprécient la qualité, la fiabilité et l'excellence à long terme.",
    explore: 'Explorer Nos Services',
    learn_more: 'En Savoir Plus',
    years_trust: 'Années de Confiance',
    about_title: 'À Propos de Ideal Deal Vietnam',
    about_heading: 'Relier les Marchés avec Intégrité et Professionnalisme',
    about_p1: "Basés au cœur de l'économie florissante du Vietnam, nous sommes spécialisés dans l'exportation de produits vietnamiens de qualité supérieure vers les marchés mondiaux. Notre parcours repose sur la confiance et une attention méticuleuse aux détails.",
    about_p2: "Nous ne facilitons pas seulement les transactions ; nous bâtissons des partenariats. En connectant les fabricants les plus fiables du Vietnam avec des acheteurs du monde entier, nous garantissons que chaque accord est 'idéal' — sûr, efficace et mutuellement bénéfique.",
    quality_first: 'Qualité d\'Abord',
    quality_desc: 'Normes d\'inspection rigoureuses.',
    global_reach: 'Portée Mondiale',
    global_desc: 'Sur les 5 continents.',
    footer_desc: 'Votre partenaire stratégique pour les produits vietnamiens de haute qualité sur le marché mondial. Fondé sur la confiance, animé par l\'excellence.',
    copyright: 'Copyright © 2025 Ideal Deal Vietnam. Tous droits réservés.',
    built_on_trust: 'Bâti sur la Confiance',
    products_title: 'Industries et Produits',
    products_desc: "Connecter l'excellence manufacturière et l'abondance naturelle du Vietnam au marché mondial avec une fiabilité inébranlable.",
    all_sectors: 'Tous les Secteurs',
    agriculture: 'Agriculture',
    manufacturing: 'Manufacture',
    consumer_goods: 'Biens de Consommation',
    our_story: 'Notre Histoire',
    redefining_trade: 'Redefini le Commerce Mondial',
    about_hero_desc: 'Ideal Deal Vietnam : Votre pont entre la qualité vietnamienne supérieure et le marché international.',
    about_excellence: 'Bâti sur la Confiance, Animé par l\'Excellence',
    about_p3: 'Bienvenue chez Ideal Deal Vietnam, votre partenaire de confiance dans le commerce mondial. Basés au cœur du paysage industriel en pleine expansion du Vietnam, nous sommes spécialisés dans l\'exportation de produits vietnamiens de haute qualité vers les marchés du monde entier.',
    about_p4: 'Avec un engagement fort envers l\'excellence, la fiabilité et les partenariats à long terme, nous connectons les meilleurs produits naturels et manufacturés du Vietnam avec des acheteurs internationaux qui privilégient avant tout la qualité et la constance.',
    our_foundation: 'Notre Fondation',
    mission: 'Notre Mission',
    mission_desc: 'Donner du pouvoir aux producteurs vietnamiens en offrant une passerelle fluide vers les marchés mondiaux, garantissant que chaque transaction repose sur une base de succès mutuel et de transparence.',
    vision: 'Our Vision',
    vision_desc: 'Devenir le principal facilitateur de commerce B2B en Asie du Sud-Est, reconnu mondialement pour établir la norme en matière d\'intégrité de la chaîne d\'approvisionnement et d\'efficacité opérationnelle.',
    values: 'Nos Valeurs',
    value1: 'Transparence à chaque étape',
    value2: 'Efficacité sans compromis',
    value3: 'Confiance profondément ancrée',
    services_hero_title: 'Nos Services',
    services_hero_desc: 'Accompagner les entreprises internationales pour une entrée fluide sur le marché vietnamien, un sourcing de qualité garantie et des solutions logistiques de bout en bout.',
    sourcing: 'Sourcing de Produits',
    sourcing_desc: 'Le Vietnam offre une richesse de produits manufacturés et naturels de haute qualité. Nous comblons le fossé en identifiant les meilleurs produits qui répondent à vos demandes spécifiques du marché.',
    supplier_id: 'Identification des Fournisseurs',
    supplier_desc: 'Trouver le bon partenaire est essentiel. Nous évaluons des milliers de fabricants locaux pour nous assurer que vous travaillez avec des fournisseurs fiables, éthiques et capables.',
    quality_assurance: 'Assurance Qualité',
    qa_desc: 'Nous sommes vos yeux et vos oreilles sur le terrain. Notre processus d\'inspection méticuleux garantit que chaque expédition répond à vos spécifications exactes.',
    ready_expand: 'Prêt à étendre votre commerce ?',
    ready_desc: 'Contactez notre équipe d\'experts dès aujourd\'hui pour discuter de vos besoins spécifiques et obtenir un devis personnalisé pour votre entreprise.',
    request_quote: 'DEMANDER UN DEVIS',
    case_studies: 'VOIR LES ÉTUDES DE CAS',
    discuss_needs: "Discutons de vos Besoins de Sourcing",
    contact_hero_desc: 'Votre partenaire de confiance dans le commerce mondial, comblant le fossé entre l\'excellence vietnamienne et la demande internationale.',
    send_message: 'Envoyez-nous un Message',
    full_name: 'Nom Complet',
    email: 'E-mail Professionnel',
    company: 'Nom de l\'Entreprise',
    message: 'Message',
    send_inquiry: 'ENVOYER LA DEMANDE',
    contact_info: 'Informations de Contact',
    office: 'Bureau Vietnam',
    address: 'District 1, Ho Chi Minh Ville, Vietnam',
    email_us: 'Nous Écrire',
    call_us: 'Nous Appeler',
    business_hours: 'Heures d\'Ouverture',
    hours: 'Lun - Ven : 8h00 - 18h00 (GMT+7)',
    view_maps: 'Voir sur Google Maps',
    success_msg: 'Merci ! Votre demande a été reçue. Notre équipe vous contactera sous peu.',
    bot_welcome: "Bonjour ! Je suis Ideal, votre assistant commercial. Comment puis-je vous aider aujourd'hui ?",
    bot_placeholder: "Posez-moi une question...",
    bot_title: "Assistant Commercial Ideal",
    full_spectrum_title: "Services Commerciaux Complets",
    full_spectrum_desc: "Nous optimisons l'ensemble du processus de la chaîne d'approvisionnement, du premier échantillon à la livraison finale à votre porte.",
    strategic_sourcing: "Sourcing Stratégique",
    strategic_sourcing_desc: "Identifier et évaluer les fabricants les plus fiables au Vietnam pour répondre à vos exigences spécifiques de produits et à vos normes de qualité.",
    qa_card_title: "Assurance Qualité",
    qa_card_desc: "Inspections sur site et protocoles de tests rigoureux pour garantir que chaque expédition répond à vos attentes avant de quitter l'entrepôt.",
    logistics_mgmt: "Logistics Management",
    logistics_mgmt_desc: "Gestion des documents douaniers complexes et coordination du fret pour assurer une livraison rapide et rentable dans le monde entier.",
    ideal_choice_title: "Le Choix Idéal pour le Commerce International B2B",
    unmatched_network: "Réseau Local Inégalé",
    unmatched_network_desc: "Accès direct aux fabricants vietnamiens de premier plan et aux fournisseurs de matières premières.",
    total_transparency: "Transparence Totale",
    total_transparency_desc: "Suivi en temps réel et communication claire et honête à chaque étape de la transaction.",
    risk_mitigation: "Atténuation des Risques",
    risk_mitigation_desc: "Nous gérons les aspects juridiques et la conformité aux normes afin que vous puissiez vous concentrer sur la croissance de votre entreprise.",
    discuss_next_deal: "Discutons de Votre Prochaine Affaire Mondiale",
    discuss_next_deal_desc: "Que vous recherchiez des fournisseurs fiables, des collaborations commerciales ou des informations sur les produits, notre équipe est prête à vous aider avec professionnalisme et efficacité.",
    subject: "Sujet",
    trust_integrity_title: "Notre Engagement",
    trust_integrity_quote: "La transparence et la confiance ne sont pas de simples mots pour nous ; ce sont les piliers sur lesquels chaque partenariat réussi est bâti.",
    invalid_email: "Veuillez entrer une adresse e-mail valide.",
    faq_title: "Foire Aux Questions",
    faq_subtitle: "Trouvez des réponses aux questions courantes sur nos solutions d'import/export.",
    q1: "Comment assurez-vous la qualité des produits ?",
    a1: "Nous effectuons des inspections sur site en plusieurs étapes, des audits d'usine et des contrôles avant expédition pour garantir que chaque produit répond aux normes internationales et à vos exigences spécifiques.",
    q2: "Quelle est la quantité minimale de commande (MOQ) typique ?",
    a2: "Les MOQ varient selon le secteur et le fabricant. Cependant, notre solide réseau de fournisseurs nous permet de négocier des conditions flexibles, facilitant souvent de petites commandes initiales pour les nouveaux partenaires internationaux.",
    q3: "Gérez-vous toute la logistique et les douanes ?",
    a3: "Oui, nous assurons une gestion logistique de bout en bout. Cela comprend la documentation, la coordination du fret et le support au dédouanement pour garantir une livraison fluide à votre destination.",
    q4: "Pouvez-vous sourcer des produits non répertoriés dans votre catalogue ?",
    a4: "Absolument. Notre vaste réseau local nous permet de sourcer pratiquement n'importe quel produit vietnamien de haute qualité. Fournissez-nous simplement vos spécifications, et nous trouverons le fournisseur idéal.",
    v5: "¿Cuáles son sus condiciones de pago estándar?",
    a5: "Nous travaillons généralement par virement T/T ou lettre de crédit (L/C) à vue. Les conditions spécifiques peuvent être négociées selon le volume et l'historique.",
    q6: "Combien de temps dure le processus de sourcing ?",
    a6: "L'identification initiale prend 5 à 7 jours ouvrables. Les cycles de production dépendent du produit, mais nous visons une efficacité maximale.",
    q7: "Proposez-vous des services OEM et marque blanche ?",
    a7: "Oui, nous aidons les marques à fabriquer leurs produits au Vietnam, de la conformité de la conception à l'emballage final.",
    track_shipment: 'Suivez Votre Expédition',
    tracking_placeholder: 'Entrez le numéro de suivi (ex: IDV12345)',
    track_now: 'SUIVRE MAINTENANT',
    shipment_not_found: 'Expédition introuvable. Veuillez vérifier le numéro.',
    status_label: 'Statut Actuel',
    location_label: 'Dernière Localisation',
    status_in_transit: 'En Transit',
    status_delivered: 'Livré',
    status_processing: 'Traitement à l\'Entrepôt',
    status_pending: 'En Attente d\'Enlèvement',
    inquiry_type: 'Type de Demande',
    general_inquiry: 'Demande Générale',
    prod_sourcing: 'Sourcing de Produits',
    partnership: 'Partenariat',
    support: 'Support',
    bot_error: 'Une erreur est survenue. Veuillez réessayer.',
    try_again: 'Réessayer',
    bot_error_quota: "Nous recevons trop de demandes. Veuillez patienter quelques secondes.",
    bot_error_offline: "Vous semblez être hors ligne. Veuillez vérifier votre connexion.",
    bot_suggestion_contact: "Contacter le support",
    ai_recommended: 'Recommandations IA',
    ai_insight: 'Aperçu IA',
    ai_analyzing: 'Analyse de vos préférences commerciales...',
    ai_no_data: 'Commencez à explorer les catégories pour obtenir des recommandations personnalisées.',
    team_title: 'Notre Équipe de Direction',
    team_subtitle: 'Découvrez les experts qui relient la qualité vietnamienne aux marchés mondiaux.',
    ceo_role: 'Fondateur & PDG',
    sourcing_role: 'Responsable du Sourcing Global',
    logistics_role: 'Directeur de la Logistique',
    qa_role: 'Responsable QA & Conformité'
  },
  ar: {
    home: 'الرئيسية',
    products: 'المنتجات',
    services: 'الخدمات',
    about: 'من نحن',
    contact: 'اتصل بنا',
    hero_title: 'شريككم الموثوق للاستيراد والتصدير في فيتنام',
    hero_subtitle: 'ربط أفضل السلع الطبيعية والمصنعة في فيتنام بالمشترين الدوليين الذين يقدرون الجودة والموثوقية والتميز طويل الأمد.',
    explore: 'استكشف خدماتنا',
    learn_more: 'تعرف علينا',
    years_trust: 'سنوات من الثقة',
    about_title: 'عن آيديل ديل فيتنام',
    about_heading: 'ربط الأسواق بنزاهة واحترافية',
    about_p1: 'مرحباً بكم في قلب الاقتصاد الفيتنامي المزدهر، نحن متخصصون في تصدير المنتجات الفيتنامية الممتازة إلى الأسواق العالمية. رحلتنا مبنية على أساس الثقة والاهتمام الدقيق بالتفاصيل.',
    about_p2: 'نحن لا نسهل المعاملات فحسب، بل نبني الشراكات. من خلال ربط المصنعين الأكثر موثوقية في فيتنام بالمشترين في جميع أنحاء العالم، نضمن أن تكون كل صفقة "مثالية" - آمنة وفعالة ومفيدة للطرفين.',
    quality_first: 'الجودة أولاً',
    quality_desc: 'معايير تفتيش صارمة.',
    global_reach: 'وصول عالمي',
    global_desc: 'عبر 5 قارات.',
    footer_desc: 'شريككم الاستراتيجي للمنتجات الفيتنامية عالية الجودة للسوق العالمي. بنيت على الثقة، ومدفوعة بالتميز.',
    copyright: 'حقوق الطبع والنشر © 2025 آيديل ديل فيتنام. جميع الحقوق محفوظة.',
    built_on_trust: 'بنيت على الثقة',
    products_title: 'الصناعات والمنتجات',
    products_desc: 'ربط التميز التصنيعي والوفرة الطبيعية في فيتنام بالسوق العالمي بموثوقية لا تتزعزع.',
    all_sectors: 'كل القطاعات',
    agriculture: 'الزراعة',
    manufacturing: 'التصنيع',
    consumer_goods: 'السلع الاستهلاكية',
    our_story: 'قصتنا',
    redefining_trade: 'إعادة تعريف التجارة العالمية',
    about_hero_desc: 'آيديل ديل فيتنام: جسركم بين الجودة الفيتنامية الممتازة والسوق الدولية.',
    about_excellence: 'بنيت على الثقة، ومدفوعة بالتميز',
    about_p3: 'مرحبًا بكم في آيديل ديل فيتنام، شريككم الموثوق في التجارة العالمية. مقرنا في قلب المشهد الصناعي المزدهر في فيتنام، نحن متخصصون في تصدير المنتجات الفيتنامية عالية الجودة إلى الأسواق في جميع أنحاء العالم.',
    about_p4: 'مع التزام قوي بالتميز والموثوقية والشراكات طويلة الأمد، نربط أفضل السلع الطبيعية والمصنعة في فيتنام بالمشترين الدوليين الذين يقدرون الجودة والاتساق قبل كل شيء.',
    our_foundation: 'أساسنا',
    mission: 'مهمتنا',
    mission_desc: 'تمكين المنتجين الفيتناميين من خلال توفير بوابة سلسة للأسواق العالمية، وضمان بناء كل صفقة على أساس النجاح المتبادل والشفافية.',
    vision: 'رؤيتنا',
    vision_desc: 'أن نصبح الميسر الرائد للتجارة بين الشركات (B2B) في جنوب شرق آسيا، والمعترف به عالميًا لوضع المعايير في نزاهة سلسلة التوريد والكفاءة التشغيلية.',
    values: 'قيمنا',
    value1: 'الشفافية في كل خطوة',
    value2: 'كفاءة لا تضاهى',
    value3: 'ثقة عميقة الجذور',
    services_hero_title: 'خدماتنا',
    services_hero_desc: 'تمكين الشركات الدولية من دخول السوق الفيتنامي بسلاسة، وتوفير مصادر مضمونة الجودة، وحلول لوجستية شاملة.',
    sourcing: 'توفير المنتجات',
    sourcing_desc: 'تقدم فيتنام ثروة من السلع المصنعة والطبيعية عالية الجودة. نحن نسد الفجوة من خلال تحديد أرقى المنتجات التي تلبي متطلبات السوق الخاصة بك.',
    supplier_id: 'تحديد الموردين',
    supplier_desc: 'العثور على الشريك المناسب أمر بالغ الأهمية. نحن نفحص آلاف المصنعين المحليين لضمان عملكم مع موردين موثوقين وأخلاقيين وقادرين.',
    quality_assurance: 'ضمان الجودة',
    qa_desc: 'نحن نمثل أعينكم وآذانكم على أرض الواقع. تضمن عملية التفتيش الدقيقة لدينا أن تلبي كل شحنة مواصفاتكم الدقيقة.',
    ready_expand: 'هل أنت مستعد لتوسيع تجارتك؟',
    ready_desc: 'اتصل بفريق خبرائنا اليوم لمناقشة متطلباتك الخاصة والحصول على عرض أسعار مخصص لعملك.',
    request_quote: 'اطلب عرض أسعار',
    case_studies: 'عرض دراسات الحالة',
    discuss_needs: 'دعونا نناقش احتياجات التوريد الخاصة بكم',
    contact_hero_desc: 'شريككم الموثوق في التجارة العالمية، نربط بين التميز الفيتنامي والطلب الدولي.',
    send_message: 'أرسل لنا رسالة',
    full_name: 'الاسم الكامل',
    email: 'البريد الإلكتروني للعمل',
    company: 'اسم الشركة',
    message: 'الرسالة',
    send_inquiry: 'إرسال الاستفسار',
    contact_info: 'معلومات الاتصال',
    office: 'مكتب فيتنام',
    address: 'المنطقة 1، مدينة هوشي منه، فيتنام',
    email_us: 'راسلنا عبر البريد',
    call_us: 'اتصل بنا',
    business_hours: 'ساعات العمل',
    hours: 'من الاثنين إلى الجمعة: 8:00 صباحًا - 6:00 مساءً (توقيت فيتنام)',
    view_maps: 'عرض على الخرائط',
    success_msg: 'شكرًا لك! تم استلام استفسارك. سيتصل بك فريقنا قريبًا.',
    bot_welcome: "مرحباً! أنا آيديل، مساعدكم التجاري. كيف يمكنني مساعدتكم اليوم؟",
    bot_placeholder: "اسألني عن أي شيء...",
    bot_title: "مساعد آيديل التجاري",
    full_spectrum_title: "خدمات تجارية متكاملة",
    full_spectrum_desc: "نحن نبسط عملية سلسلة التوريد بأكملها، من العينة الأولى إلى التسليم النهائي عند باب منزلك.",
    strategic_sourcing: "التوريد الاستراتيجي",
    strategic_sourcing_desc: "تحديد وفحص المصنعين الأكثر موثوقية في فيتنام لمطابقة متطلبات المنتج ومعايير الجودة الخاصة بك.",
    qa_card_title: "ضمان الجودة",
    qa_card_desc: "عمليات التفتيش في الموقع وبروتوكولات الاختبار الصارمة لضمان أن كل شحنة تلبي توقعاتك قبل مغادرة المستودع.",
    logistics_mgmt: "إدارة اللوجستيات",
    logistics_mgmt_desc: "التعامل مع الوثائق الجمركية المعقدة وتنسيق الشحن لضمان التسليم في الوقت المناسب وبأقل تكلفة في جميع أنحاء العالم.",
    ideal_choice_title: "الخيار المثالي للتجارة الدولية بين الشركات (B2B)",
    unmatched_network: "شبكة محلية لا تضاهى",
    unmatched_network_desc: "وصول مباشر إلى كبار المصنعين وموردي المواد الخام في فيتنام.",
    total_transparency: "شفافية مطلقة",
    total_transparency_desc: "تتبع في الوقت الفعلي وتواصل واضح وصادق في كل مرحلة من مراحل الصفقة.",
    risk_mitigation: "تخفيف المخاطر",
    risk_mitigation_desc: "نحن نتعامل مع الجوانب القانونية والامتثال للمعايير حتى ت تمكن من التركيز على نمو عملك.",
    discuss_next_deal: "لنناقش صفقتك العالمية القادمة",
    discuss_next_deal_desc: "سواء كنت تبحث عن موردين موثوقين، أو تعاون تجاري، أو معلومات عن المنتج، فإن فريقنا مستعد للمساعدة باحترافية وكفاءة.",
    subject: "الموضوع",
    trust_integrity_title: "التزامنا",
    trust_integrity_quote: "الشفافية والثقة ليست مجرد كلمات بالنسبة لنا؛ إنها الركائز التي تُبنى عليها كل شراكة ناجحة.",
    invalid_email: "يرجى إدخل عنوان بريد إلكتروني صحيح.",
    faq_title: "الأسئلة الشائعة",
    faq_subtitle: "ابحث عن إجابات للأسئلة الشائعة حول حلول الاستيراد والتصدير لدينا.",
    q1: "كيف تضمنون جودة المنتج؟",
    a1: "نقوم بإجراء عمليات تفتيش ميدانية متعددة المراحل، وتدقيق المصانع، وفحوصات ما قبل الشحن لضمان مطابقة كل منتج للمعايير الدولية ومتطلباتكم الخاصة.",
    q2: "ما هو الحد الأدنى المعتاد لكمية الطلب (MOQ)؟",
    a2: "تختلف كميات الطلب الدنيا حسب الصناعة والشركة المصنعة. ومع ذلك، تتيح لنا شبكة موردينا القوية التفاوض على شروط مرنة، مما يسهل في كثير من الأحيان الطلبات الأولية الصغيرة للشركاء الدوليين الجدد.",
    q3: "هل تتعاملون مع جميع الشؤون اللوجستية والجمارك؟",
    a3: "نعم، نحن نقدم إدارة لوجستية شاملة. يشمل ذلك الوثائق، وتنسيق الشحن، ودعم التخليص الجمركي لضمان التسليم السلس إلى وجهتكم.",
    q4: "هل يمكنك توفير منتجات غير مدرجة في الكتالوج الخاص بك؟",
    a4: "بالتأكيد. تتيح لنا شبكتنا المحلية الواسعة توفير أي منتج فيتنامي عالي الجودة تقريبًا. ما عليك سوى تزويدنا بمواصفاتك، وسنجد المورد المثالي.",
    q5: "ما هي شروط الدفع القياسية لديكم؟",
    a5: "نتعامل عادةً عبر التحويل البرقي (T/T) أو الاعتماد المستندي (L/C). يمكن التفاوض على شروط محددة بناءً على حجم الطلب وتاريخ الشراكة.",
    q6: "كم يستغرق وقت عملية التوريد عادةً؟",
    a6: "يستغرق تحديد المورد الأولي عادةً من 5 إلى 7 أيام عمل. تعتمد دورات الإنتاج على نوع المنتج، لكننا نسعى لتحقيق أقصى قدر من الكفاءة.",
    q7: "هل تقدمون خدمات التصنيع للغير (OEM) والعلامات التجارية الخاصة؟",
    a7: "نعم، نحن متخصصون في مساعدة العلامات التجارية على تصنيع منتجاتها في فيتنام، مع تقديم الدعم الكامل من التصميم وحتى التغليف النهائي.",
    track_shipment: 'تتبع شحنتك',
    tracking_placeholder: 'أدخل رقم التتبع (مثال: IDV12345)',
    track_now: 'تتبع الآن',
    shipment_not_found: 'لم يتم العثور على الشحنة. يرجى التأكد من الرقم.',
    status_label: 'الحالة الحالية',
    location_label: 'آخر موقع',
    status_in_transit: 'قيد الانتقال',
    status_delivered: 'تم التسليم',
    status_processing: 'قيد التجهيز في المستودع',
    status_pending: 'بانتظار الاستلام',
    inquiry_type: 'نوع الاستفسار',
    general_inquiry: 'استفسار عام',
    prod_sourcing: 'توريد المنتجات',
    partnership: 'شراكة',
    support: 'الدعم',
    bot_error: 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
    try_again: 'إعادة المحاولة',
    bot_error_quota: "نحن نتلقى الكثير من الطلبات حالياً. يرجى الانتظار بضع ثوانٍ.",
    bot_error_offline: "يبدو أنك غير متصل بالإنترنت. يرجى التحقق من اتصالك.",
    bot_suggestion_contact: "اتصل بالدعم",
    ai_recommended: 'توصيات مدعومة بالذكاء الاصطناعي',
    ai_insight: 'رؤية الذكاء الاصطناعي',
    ai_analyzing: 'جاري تحليل تفضيلاتك التجارية...',
    ai_no_data: 'ابدأ في استكشاف الفئات للحصول على توصيات منتجات مخصصة.',
    team_title: 'فريق القيادة لدينا',
    team_subtitle: 'تعرف على الخبراء الذين يربطون الجودة الفيتنامية بالأسواق العالمية.',
    ceo_role: 'المؤسس والرئيس التنفيذي',
    sourcing_role: 'رئيس التوريد العالمي',
    logistics_role: 'مدير اللوجستيات',
    qa_role: 'مدير ضمان الجودة والامتثال'
  },
  vi: {
    home: 'TRANG CHỦ',
    products: 'SẢN PHẨM',
    services: 'DỊCH VỤ',
    about: 'VỀ CHÚNG TÔI',
    contact: 'LIÊN HỆ',
    hero_title: 'Đối Tác Xuất Nhập Khẩu Tin Cậy Của Bạn Tại Việt Nam',
    hero_subtitle: "Kết nối hàng hóa tự nhiên và sản xuất tốt nhất của Việt Nam với các đối tác quốc tế coi trọng chất lượng, độ tin cậy và sự xuất sắc lâu dài.",
    explore: 'Khám Phá Dịch Vụ',
    learn_more: 'Tìm Hiểu Thêm',
    years_trust: 'Năm Tin Tưởng',
    about_title: 'Về Ideal Deal Việt Nam',
    about_heading: 'Kết Nối Thị Trường Với Sự Chính Trực Và Chuyên Nghiệp',
    about_p1: "Tọa lạc tại trung tâm nền kinh tế đang bùng nổ của Việt Nam, chúng tôi chuyên xuất khẩu các sản phẩm Việt Nam cao cấp ra thị trường toàn cầu. Hành trình của chúng tôi được xây dựng trên nền tảng của sự tin tưởng và sự chú ý tỉ mỉ đến từng chi tiết.",
    about_p2: "Chúng tôi không chỉ thực hiện các giao dịch; chúng tôi xây dựng quan hệ đối tác. Bằng cách kết nối các nhà sản xuất đáng tin cậy nhất Việt Nam với người mua trên toàn thế giới, chúng tôi đảm bảo mọi giao dịch đều 'lý tưởng'—an toàn, hiệu quả và đôi bên cùng có lợi.",
    quality_first: 'Chất Lượng Hàng Đầu',
    quality_desc: 'Tiêu chuẩn kiểm tra nghiêm ngặt.',
    global_reach: 'Tầm Vóc Toàn Cầu',
    global_desc: 'Trải khắp 5 châu lục.',
    footer_desc: 'Đối tác chiến lược của bạn cho các sản phẩm Việt Nam chất lượng cao ra thị trường toàn cầu. Xây dựng trên sự tin tưởng, thúc đẩy bởi sự xuất sắc.',
    copyright: 'Bản quyền © 2025 Ideal Deal Việt Nam. Bảo lưu mọi quyền.',
    built_on_trust: 'Xây Dựng Trên Sự Tin Tưởng',
    products_title: 'Ngành Hàng & Sản Phẩm',
    products_desc: "Kết nối tinh hoa sản xuất và sự trù phú của thiên nhiên Việt Nam với thị trường toàn cầu bằng sự tin cậy kiên định.",
    all_sectors: 'Tất Cả Ngành',
    agriculture: 'Nông Nghiệp',
    manufacturing: 'Sản Xuất',
    consumer_goods: 'Hàng Tiêu Dùng',
    our_story: 'Câu Chuyện Của Chúng Tôi',
    redefining_trade: 'Định Nghĩa Lại Thương Mại Toàn Cầu',
    about_hero_desc: 'Ideal Deal Việt Nam: Cầu nối giữa chất lượng cao cấp Việt Nam và thị trường quốc tế.',
    about_excellence: 'Xây Dựng Trên Sự Tin Tưởng, Thúc Đẩy Bởi Sự Xuất Sắc',
    about_p3: 'Chào mừng đến với Ideal Deal Việt Nam, đối tác tin cậy của bạn trong thương mại toàn cầu. Tọa lạc tại trung tâm bối cảnh công nghiệp đang bùng nổ của Việt Nam, chúng tôi chuyên xuất khẩu các sản phẩm Việt Nam chất lượng cao ra thị trường thế giới.',
    about_p4: 'Với cam kết mạnh mẽ về sự xuất sắc, độ tin cậy và quan hệ đối tác lâu dài, chúng tôi kết nối những mặt hàng tự nhiên và sản xuất tốt nhất của Việt Nam với các người mua quốc tế coi trọng chất lượng và sự nhất quán trên hết.',
    our_foundation: 'Nền Tảng Của Chúng Tôi',
    mission: 'Sứ Mệnh',
    mission_desc: 'Trao quyền cho các nhà sản xuất Việt Nam bằng cách cung cấp con đường liền mạch ra thị trường toàn cầu, đảm bảo mọi giao dịch đều được xây dựng trên nền tảng của sự thành công chung và minh bạch.',
    vision: 'Tầm Nhìn',
    vision_desc: 'Trở thành đơn vị hỗ trợ thương mại B2B hàng đầu tại Đông Nam Á, được công nhận toàn cầu vì thiết lập các tiêu chuẩn về tính chính trực của chuỗi cung ứng và hiệu quả hoạt động.',
    values: 'Giá Trị Cốt Lõi',
    value1: 'Minh bạch trong mọi bước',
    value2: 'Hiệu quả không thỏa hiệp',
    value3: 'Sự tin tưởng sâu sắc',
    services_hero_title: 'Dịch Vụ Của Chúng Tôi',
    services_hero_desc: 'Trao quyền cho các doanh nghiệp quốc tế với sự gia nhập thị trường Việt Nam liền mạch, nguồn hàng đảm bảo chất lượng và giải pháp hậu cần toàn diện.',
    sourcing: 'Tìm Kiếm Nguồn Hàng',
    sourcing_desc: 'Việt Nam mang đến sự phong phú về hàng hóa sản xuất và tự nhiên chất lượng cao. Chúng tôi xóa bỏ khoảng cách bằng cách xác định các sản phẩm tốt nhất đáp ứng nhu cầu thị trường cụ thể của bạn.',
    supplier_id: 'Xác Định Nhà Cung Cấp',
    supplier_desc: 'Tìm kiếm đối tác phù hợp là yếu tố sống còn. Chúng tôi thẩm định hàng ngàn nhà sản xuất địa phương để đảm bảo bạn làm việc với những nhà cung cấp đáng tin cậy, có đạo đức và năng lực.',
    quality_assurance: 'Đảm Bảo Chất Lượng',
    qa_desc: 'Chúng tôi đóng vai trò là đôi mắt và đôi tai của bạn tại hiện trường. Quy trình kiểm tra tỉ mỉ của chúng tôi đảm bảo mọi lô hàng đều đáp ứng các thông số kỹ thuật chính xác của bạn.',
    ready_expand: 'Sẵn sàng mở rộng giao thương?',
    ready_desc: 'Liên hệ với đội ngũ chuyên gia của chúng tôi ngay hôm nay để thảo luận về các yêu cầu cụ thể và nhận báo giá phù hợp cho doanh nghiệp của bạn.',
    request_quote: 'YÊU CẦU BÁO GIÁ',
    case_studies: 'XEM DỰ ÁN TIÊU BIỂU',
    discuss_needs: "Hãy Thảo Luận Về Nhu Cầu Nguồn Hàng Của Bạn",
    contact_hero_desc: 'Đối tác tin cậy của bạn trong thương mại toàn cầu, kết nối tinh hoa Việt Nam với nhu cầu quốc tế.',
    send_message: 'Gửi Tin Nhắn Cho Chúng Tôi',
    full_name: 'Họ và Tên',
    email: 'Email Công Việc',
    company: 'Tên Công Ty',
    message: 'Nội Dung',
    send_inquiry: 'GỬI YÊU CẦU',
    contact_info: 'Thông Tin Liên Hệ',
    office: 'Văn Phòng Việt Nam',
    address: 'Quận 1, TP. Hồ Chí Minh, Việt Nam',
    email_us: 'Gửi Email',
    call_us: 'Gọi Cho Chúng Tôi',
    business_hours: 'Giờ Làm Việc',
    hours: 'Thứ 2 - Thứ 6: 8:00 SA - 6:00 CH (GMT+7)',
    view_maps: 'Xem Trên Bản Đồ',
    success_msg: 'Cảm ơn bạn! Yêu cầu của bạn đã được tiếp nhận. Đội ngũ của chúng tôi sẽ liên hệ với bạn sớm nhất có thể.',
    bot_welcome: "Chào bạn! Tôi là Ideal, trợ lý thương mại của bạn. Tôi có thể giúp gì cho bạn hôm nay?",
    bot_placeholder: "Hỏi tôi bất cứ điều gì...",
    bot_title: "Trợ Lý Thương Mại Ideal",
    full_spectrum_title: "Dịch Vụ Thương Mại Toàn Diện",
    full_spectrum_desc: "Chúng tôi tinh gọn toàn bộ quy trình chuỗi cung ứng, từ mẫu hàng đầu tiên đến khi giao hàng cuối cùng tại kho của bạn.",
    strategic_sourcing: "Tìm Kiếm Nguồn Hàng Chiến Lược",
    strategic_sourcing_desc: "Xác định và thẩm định các nhà sản xuất đáng tin cậy nhất tại Việt Nam để phù hợp với yêu cầu sản phẩm và tiêu chuẩn chất lượng cụ thể của bạn.",
    qa_card_title: "Đảm Bảo Chất Lượng",
    qa_card_desc: "Kiểm tra tại hiện trường và các quy trình thử nghiệm nghiêm ngặt để đảm bảo mọi lô hàng đều đáp ứng mong đợi của bạn trước khi rời kho.",
    logistics_mgmt: "Quản Lý Hậu Cần",
    logistics_mgmt_desc: "Xử lý các chứng từ hải quan phức tạp và điều phối vận tải để đảm bảo giao hàng đúng hạn và tiết kiệm chi phí trên toàn thế giới.",
    ideal_choice_title: "Lựa Chọn Lý Tưởng Cho Thương Mại Quốc tế B2B",
    unmatched_network: "Mạng Lưới Địa Phương Không Đối Thủ",
    unmatched_network_desc: "Tiếp cận trực tiếp với các nhà sản xuất Việt Nam cấp cao và các nhà cung cấp nguyên liệu thô.",
    total_transparency: "Minh Bạch Tuyệt Đối",
    total_transparency_desc: "Theo dõi thời gian thực và giao tiếp rõ ràng, trung thực ở mọi giai đoạn của giao dịch.",
    risk_mitigation: "Giảm Thiểu Rủi Ro",
    risk_mitigation_desc: "Chúng tôi xử lý các vấn đề pháp lý và tuân thủ tiêu chuẩn để bạn có thể tập trung vào phát triển kinh doanh.",
    discuss_next_deal: "Thảo Luận Về Giao Dịch Toàn Cầu Tiếp Theo",
    discuss_next_deal_desc: "Cho dù bạn đang tìm kiếm nhà cung cấp tin cậy, hợp tác kinh doanh hay thông tin sản phẩm, đội ngũ của chúng tôi luôn sẵn sàng hỗ trợ chuyên nghiệp.",
    subject: "Chủ Đề",
    trust_integrity_title: "Cam Kết Của Chúng Tôi",
    trust_integrity_quote: "Sự minh bạch và tin tưởng không chỉ là lời nói đối với chúng tôi; đó là những trụ cột để xây dựng mọi quan hệ đối tác thành công.",
    invalid_email: "Vui lòng nhập địa chỉ email hợp lệ.",
    faq_title: "Câu Hỏi Thường Gặp",
    faq_subtitle: "Tìm câu trả lời cho các thắc mắc phổ biến về giải pháp xuất nhập khẩu của chúng tôi.",
    q1: "Làm thế nào để bạn đảm bảo chất lượng sản phẩm?",
    a1: "Chúng tôi thực hiện kiểm tra tại hiện trường nhiều giai đoạn, thẩm định nhà máy và kiểm tra trước khi giao hàng để đảm bảo mọi sản phẩm đều đáp ứng tiêu chuẩn quốc tế và yêu cầu cụ thể của bạn.",
    q2: "Số lượng đặt hàng tối thiểu (MOQ) thông thường là bao nhiêu?",
    a2: "MOQs thay đổi tùy theo ngành hàng và nhà sản xuất. Tuy nhiên, mạng lưới nhà cung cấp mạnh mẽ của chúng tôi cho phép thương lượng các điều khoản linh hoạt, thường hỗ trợ các đơn hàng ban đầu nhỏ hơn cho các đối tác quốc tế mới.",
    q3: "Bạn có xử lý toàn bộ hậu cần và thủ tục hải quan không?",
    a3: "Có, chúng tôi cung cấp dịch vụ quản lý hậu cần trọn gói. Điều này bao gồm xử lý chứng từ, điều phối vận tải và hỗ trợ thông quan để đảm bảo giao hàng thông suốt đến điểm đích của bạn.",
    q4: "Bạn có thể tìm nguồn hàng không có trong danh mục của mình không?",
    a4: "Chắc chắn rồi. Mạng lưới địa phương sâu rộng cho phép chúng tôi tìm kiếm hầu như bất kỳ sản phẩm Việt Nam chất lượng cao nào. Chỉ cần cung cấp thông số kỹ thuật của bạn, và chúng tôi sẽ tìm nhà cung cấp lý tưởng.",
    q5: "Phương thức thanh toán tiêu chuẩn là gì?",
    a5: "Chúng tôi thường sử dụng T/T hoặc L/C trả ngay. Các điều khoản cụ thể có thể thương lượng dựa trên khối lượng đơn hàng và lịch sử hợp tác.",
    q6: "Quy trình tìm nguồn hàng thường mất bao lâu?",
    a6: "Việc xác định nhà cung cấp ban đầu mất 5-7 ngày làm việc. Chu kỳ sản xuất tùy thuộc vào loại sản phẩm, nhưng chúng tôi luôn tối ưu hiệu quả.",
    q7: "Bạn có cung cấp dịch vụ OEM và nhãn hiệu riêng không?",
    a7: "Giúp các thương hiệu sản xuất sản phẩm tại Việt Nam, từ tuân thủ thiết kế đến đóng gói hoàn thiện.",
    track_shipment: 'Theo Dõi Đơn Hàng',
    tracking_placeholder: 'Nhập mã vận đơn (VD: IDV12345)',
    track_now: 'THEO DÕI NGAY',
    shipment_not_found: 'Không tìm thấy đơn hàng. Vui lòng kiểm tra lại mã.',
    status_label: 'Trạng thái hiện tại',
    location_label: 'Vị trí cuối',
    status_in_transit: 'Đang vận chuyển',
    status_delivered: 'Đã giao hàng',
    status_processing: 'Đang xử lý tại kho',
    status_pending: 'Chờ lấy hàng',
    inquiry_type: 'Loại yêu cầu',
    general_inquiry: 'Yêu cầu chung',
    prod_sourcing: 'Nguồn hàng sản phẩm',
    partnership: 'Hợp tác',
    support: 'Hỗ trợ',
    bot_error: 'Đã có lỗi xảy ra. Vui lòng thử lại.',
    try_again: 'Thử lại',
    bot_error_quota: "Hệ thống đang quá tải. Vui lòng đợi vài giây.",
    bot_error_offline: "Có vẻ bạn đang ngoại tuyến. Vui lòng kiểm tra kết nối.",
    bot_suggestion_contact: "Liên hệ hỗ trợ",
    ai_recommended: 'Gợi Ý Từ AI',
    ai_insight: 'Phân Tích AI',
    ai_analyzing: 'Đang phân tích sở thích giao dịch của bạn...',
    ai_no_data: 'Hãy khám phá các ngành hàng để nhận gợi ý sản phẩm cá nhân hóa.',
    team_title: 'Đội Ngũ Lãnh Đạo',
    team_subtitle: 'Gặp gỡ những chuyên gia kết nối chất lượng Việt Nam với thị trường toàn cầu.',
    ceo_role: 'Người sáng lập & CEO',
    sourcing_role: 'Trưởng bộ phận Tìm kiếm Nguồn hàng Toàn cầu',
    logistics_role: 'Giám đốc Hậu cần',
    qa_role: 'Quản lý QA & Tuân thủ'
  },
  zh: {
    home: '首页',
    products: '产品系列',
    services: '我们的服务',
    about: '关于我们',
    contact: '联系我们',
    hero_title: '您在越南值得信赖的进出口合作伙伴',
    hero_subtitle: '将越南最优质的天然产品和制造商品与重视质量、可靠性和长期卓越性能的国际买家联系起来。',
    explore: '探索我们的服务',
    learn_more: '了解更多',
    years_trust: '多年的信任',
    about_title: '关于越南 Ideal Deal',
    about_heading: '以诚信和专业精神桥接市场',
    about_p1: '我们位于越南蓬勃发展的经济中心，专注于将越南优质产品出口到全球市场。我们的旅程建立在信任和对细节细致入微的关注基础之上。',
    about_p2: '我们不只是促进交易；我们建立合作伙伴关系。通过将越南最可靠的制造商与全球买家联系起来，我们确保每一笔交易都是“理想的”——安全、高效且互利互惠。',
    quality_first: '质量第一',
    quality_desc: '严格的检验标准。',
    global_reach: '全球覆盖',
    global_desc: '覆盖五大洲。',
    footer_desc: '您将越南高质量产品推向全球市场的战略合作伙伴。建立在信任之上，由卓越驱动。',
    copyright: '版权所有 © 2025 Ideal Deal Vietnam。保留所有权利。',
    built_on_trust: '建立在信任之上',
    products_title: '行业与产品',
    products_desc: '以坚定不移的可靠性将越南的卓越制造和自然丰富性与全球市场联系起来。',
    all_sectors: '所有行业',
    agriculture: '农业',
    manufacturing: '制造业',
    consumer_goods: '消费品',
    our_story: '我们的故事',
    redefining_trade: '重新定义全球贸易',
    about_hero_desc: 'Ideal Deal Vietnam：您在越南优质品质与国际市场之间的桥梁。',
    about_excellence: '建立在信任之上，由卓越驱动',
    about_p3: '欢迎来到 Ideal Deal Vietnam，您在全球贸易中值得信赖的合作伙伴。我们总部位于越南蓬勃发展的工业景观中心，专注于将高质量的越南产品出口到世界各地的市场。',
    about_p4: '凭借对卓越、可靠性和长期合作伙伴关系的坚定承诺，我们将越南最好的天然和制成品与最重视质量和一致性的国际买家联系起来。',
    our_foundation: '我们的基础',
    mission: '我们的使命',
    mission_desc: '通过为越南生产商提供通往全球市场的无缝门户，确保每一笔交易都建立在共同成功和透明的基础之上。',
    vision: '我们的愿景',
    vision_desc: '成为东南亚领先的 B2B 贸易促进者，因在供应链完整性和运营效率方面设定标准而享誉全球。',
    values: '我们的价值观',
    value1: '每一步都保持透明',
    value2: '毫不妥协的效率',
    value3: '根深蒂固的信任',
    services_hero_title: '我们的服务',
    services_hero_desc: '为国际企业提供无缝的越南 market 进入、质量保证的采购和端到端的物流解决方案。',
    sourcing: '产品采购',
    sourcing_desc: '越南提供了丰富的优质制成品和天然商品。我们通过识别满足您特定市场需求的最佳产品来弥合差距。',
    supplier_id: '供应商识别',
    supplier_desc: '寻找合适的合作伙伴至关重要。我们审查数以千计的当地制造商，以确保您与可靠、合乎道德且有能力的供应商合作。',
    quality_assurance: '质量保证',
    qa_desc: '我们充当您在现场的眼睛和耳朵。我们细致的检验过程确保每批货物都符合您的确切规格。',
    ready_expand: '准备好扩大您的贸易了吗？',
    ready_desc: '今天就联系我们的专家团队，讨论您的具体要求，并为您的业务获取量身定制的报价。',
    request_quote: '索取报价',
    case_studies: '查看案例研究',
    discuss_needs: "让我们讨论您的采购需求",
    contact_hero_desc: '您在全球贸易中值得信赖的合作伙伴，桥接越南的卓越品质与国际需求。',
    send_message: '给我们发消息',
    full_name: '全名',
    email: '商业邮箱',
    company: '公司名称',
    message: '留言内容',
    send_inquiry: '发送咨询',
    contact_info: '联系信息',
    office: '越南办事处',
    address: '越南胡志明市第一区',
    email_us: '给我们发邮件',
    call_us: '致电我们',
    business_hours: '营业时间',
    hours: '周一至周五：上午 8:00 - 下午 6:00 (GMT+7)',
    view_maps: '在地图上查看',
    success_msg: '谢谢！您的咨询已收到。我们的团队将尽快与您联系。',
    bot_welcome: "你好！我是 Ideal，您的贸易助手。今天我能为您做些什么？",
    bot_placeholder: "问我任何问题...",
    bot_title: "Ideal 贸易助手",
    full_spectrum_title: "全方位贸易服务",
    full_spectrum_desc: "我们简化了从第一个样品到送到您家门口的最终交付的整个供应链流程。",
    strategic_sourcing: "战略采购",
    strategic_sourcing_desc: "识别并审查越南最可靠的制造商，以匹配您的特定产品要求和质量标准。",
    qa_card_title: "质量保证",
    qa_card_desc: "现场检查和严格的测试协议，确保每批货物在离开仓库前都符合您的预期。",
    logistics_mgmt: "物流管理",
    logistics_mgmt_desc: "处理复杂的海关文件并协调货运，确保全球范围内及时且具有成本效益的交付。",
    ideal_choice_title: "B2B 国际贸易的理想选择",
    unmatched_network: "无与伦比的本地网络",
    unmatched_network_desc: "直接接触越南顶级制造商和原材料供应商。",
    total_transparency: "完全透明",
    total_transparency_desc: "在交易的每个阶段进行实时跟踪和清晰、诚实的沟通。",
    risk_mitigation: "风险缓解",
    risk_mitigation_desc: "我们处理法律事务和标准合规性，以便您可以专注于发展您的业务。",
    discuss_next_deal: "让我们讨论您的下一笔全球交易",
    discuss_next_deal_desc: "无论您是在寻找可靠的供应商、业务合作还是产品信息，我们的团队都准备好以专业和高效的态度为您提供帮助。",
    subject: "主题",
    trust_integrity_title: "我们的承诺",
    trust_integrity_quote: "透明和信任对我们来说不仅仅是词汇；它们是每一个成功合作伙伴关系赖以建立的支柱。",
    invalid_email: "请输入有效的电子邮件地址。",
    faq_title: "常见问题解答",
    faq_subtitle: "寻找关于我们进出口解决方案常见问题的答案。",
    q1: "你们如何确保产品质量？",
    a1: "我们进行多阶段的现场检查、工厂审核和装船前检查，以确保每件产品都符合国际标准和您的具体要求。",
    q2: "典型的最小起订量 (MOQ) 是多少？",
    a2: "起订量因行业和制造商而异。然而，我们强大的供应商 network 使我们能够谈判灵活的条款，通常为新的国际合作伙伴提供较小的初始订单。",
    q3: "你们处理所有的物流和海关吗？",
    a3: "是的，我们提供端到端的物流管理。这包括文件处理、货运协调和清关支持，以确保顺利交付到您的目的地。",
    q4: "你们能采购不在目录中的产品吗？",
    a4: "当然可以。我们广泛的本地网络使我们能够采购几乎任何高质量的越南产品。只需向我们提供您的规格，我们就会找到理想的供应商。",
    q5: "你们的标准付款条件是什么？",
    a5: "我们通常采用电汇 (T/T) 或即期信用证 (L/C) 在线兑付。具体条款可根据订单量和合作历史进行协商。",
    q6: "采购流程通常需要多长时间？",
    a6: "初步供应商识别通常需要 5-7 个工作日。完整生产周期取决于产品类型，但我们致力于实现最高效率。",
    q7: "你们提供 OEM 或自有品牌服务吗？",
    a7: "帮助品牌在越南制造产品，提供从设计合规到最终包装的全方位支持。",
    track_shipment: '追踪您的货物',
    tracking_placeholder: '输入追踪号码 (例如: IDV12345)',
    track_now: '立即查询',
    shipment_not_found: '未找到货物。请检查追踪号码。',
    status_label: '当前状态',
    location_label: '最后位置',
    status_in_transit: '运输中',
    status_delivered: '已送达',
    status_processing: '仓库处理中',
    status_pending: '待取件',
    inquiry_type: '咨询类型',
    general_inquiry: '一般咨询',
    prod_sourcing: '产品采购',
    partnership: '合作伙伴',
    support: '支持',
    bot_error: '出错了。请再试一次。',
    try_again: '再试一次',
    bot_error_quota: "请求过多，请稍等几秒钟再试。",
    bot_error_offline: "您似乎处于离线状态，请检查网络连接。",
    bot_suggestion_contact: "联系支持",
    ai_recommended: 'AI 智能推荐',
    ai_insight: 'AI 洞察',
    ai_analyzing: '正在分析您的贸易偏好...',
    ai_no_data: '开始浏览分类以获取个性化的产品推荐。',
    team_title: '我们的领导团队',
    team_subtitle: '认识将越南品质与全球市场联系起来的专家。',
    ceo_role: '创始人兼首席执行官',
    sourcing_role: '全球采购负责人',
    logistics_role: '物流总监',
    qa_role: '质量保证与合规经理'
  },
  es: {
    home: 'INICIO',
    products: 'PRODUCTOS',
    services: 'SERVICIOS',
    about: 'SOBRE NOSOTROS',
    contact: 'CONTÁCTENOS',
    hero_title: 'Su Socio de Confianza en Importación y Exportación en Vietnam',
    hero_subtitle: "Conectando los mejores productos naturales y manufacturados de Vietnam con compradores internacionales que valoran la calidad, la confiabilidad y la excelencia a largo plazo.",
    explore: 'Explore Nuestros Servicios',
    learn_more: 'Saber Más',
    years_trust: 'Años de Confianza',
    about_title: 'Sobre Ideal Deal Vietnam',
    about_heading: 'Uniendo Mercados con Integriad y Profesionalismo',
    about_p1: "Ubicados en el corazón de la próspera economía de Vietnam, nos especializamos en la exportación de productos vietnamitas premium a los mercados globales. Nuestro viaje se basa en la confianza y la atención meticulosa a los detalles.",
    about_p2: "No solo facilitamos transacciones; construimos asociaciones. Al conectar a los fabricantes más confiables de Vietnam con compradores de todo el mundo, garantizamos que cada trato sea 'ideal': seguro, eficiente y muatuamente beneficioso.",
    quality_first: 'Calidad Primero',
    quality_desc: 'Estándares de inspección rigurosos.',
    global_reach: 'Alcance Global',
    global_desc: 'En los 5 continentes.',
    footer_desc: 'Su socio estratégico para productos vietnamitas de alta calidad para el mercado global. Basado en la confianza, impulsado por la excelencia.',
    copyright: 'Copyright © 2025 Ideal Deal Vietnam. Todos los derechos reservados.',
    built_on_trust: 'Basado en la Confianza',
    products_title: 'Industrias y Productos',
    products_desc: "Conectando la excelencia manufacturera y la abundancia natural de Vietnam con el mercado global con una confiabilidad inquebrantable.",
    all_sectors: 'Todos los Sectores',
    agriculture: 'Agricultura',
    manufacturing: 'Manufactura',
    consumer_goods: 'Bienes de Consumo',
    our_story: 'Nuestra Historia',
    redefining_trade: 'Redefiniendo el Comercio Global',
    about_hero_desc: 'Ideal Deal Vietnam: Su puente entre la calidad premium vietnamita y el mercado internacional.',
    about_excellence: 'Basado en la Confianza, Impulsado por la Excelencia',
    about_p3: 'Bienvenido a Ideal Deal Vietnam, su socio de confianza en el comercio global. Con sede en el corazón del próspero paisaje industrial de Vietnam, nos especializamos en la exportación de productos vietnamitas de alta calidad a mercados de todo el mundo.',
    about_p4: 'Con un fuerte compromiso con la excelencia, la confiabilidad y las asociaciones a largo plazo, conectamos los mejores productos naturales y manufacturados de Vietnam con compradores internacionales que valoran la calidad y la consistencia por encima de todo.',
    our_foundation: 'Nuestra Fundación',
    mission: 'Nuestra Misión',
    mission_desc: 'Empoderar a los productores vietnamitas proporcionando una puerta de entrada fluida a los mercados globales, asegurando que cada trato se base en una base de éxito mutuo y transparencia.',
    vision: 'Nuestra Vision',
    vision_desc: 'Convertirnos en el facilitador líder de comercio B2B en el sudeste asiático, reconocido mundialmente por establecer el estándar en la integridad de la cadena de suministro y la eficiencia operativa.',
    values: 'Nuestros Valores',
    value1: 'Transparencia en cada paso',
    value2: 'Eficiencia sin compromisos',
    value3: 'Confianza profundamente arraigada',
    services_hero_title: 'Nuestros Servicios',
    services_hero_desc: 'Empoderando a las empresas internacionales con una entrada fluida al mercado vietnamita, abastecimiento con garantía de calidad y soluciones logísticas de extremo a extremo.',
    sourcing: 'Abastecimiento de Productos',
    sourcing_desc: 'Vietnam ofrece una gran cantidad de productos naturales y manufacturados de alta calidad. Cerramos la brecha identificando los mejores productos que cumplen con las demandas específicas de su mercado.',
    supplier_id: 'Identificación de Proveedores',
    supplier_desc: 'Encontrar el socio adecuado es crítico. Evaluamos a miles de fabricantes locales para asegurar que trabaje con proveedores confiables, éticos y capaces.',
    quality_assurance: 'Garantía de Calidad',
    qa_desc: 'Actuamos como sus ojos y oídos sobre el terreno. Nuestro meticuloso proceso de inspección garantiza que cada envío cumpla con sus especificaciones exactas.',
    ready_expand: '¿Listo para expandir su comercio?',
    ready_desc: 'Contacte a nuestro equipo de expertos hoy mismo para discutir sus requisitos específicos y obtener una cotización a medida para su negocio.',
    request_quote: 'SOLICITAR COTIZACIÓN',
    case_studies: 'VER ESTUDIOS DE CASO',
    discuss_needs: "Hablemos de sus Necesidades de Abastecimiento",
    contact_hero_desc: 'Su socio de confianza en el comercio global, cerrando la brecha entre la excelencia vietnamita y la demanda internacional.',
    send_message: 'Envíenos un Mensaje',
    full_name: 'Nombre Completo',
    email: 'Correo Electrónico Comercial',
    company: 'Nombre de la Empresa',
    message: 'Mensaje',
    send_inquiry: 'ENVIAR CONSULTA',
    contact_info: 'Información de Contacto',
    office: 'Oficina en Vietnam',
    address: 'Distrito 1, Ciudad Ho Chi Minh, Vietnam',
    email_us: 'Envíenos un Correo',
    call_us: 'Llámenos',
    business_hours: 'Horario Comercial',
    hours: 'Lun - Vie: 8:00 AM - 6:00 PM (GMT+7)',
    view_maps: 'Ver en Mapas',
    success_msg: '¡Gracias! Su consulta ha sido recibida. Nuestro equipo se pondrá en contacto con usted en breve.',
    bot_welcome: "¡Hola! Soy Ideal, su asistente de comercio. ¿Cómo puedo ayudarle hoy?",
    bot_placeholder: "Pregúntame cualquier cosa...",
    bot_title: "Asistente de Comercio Ideal",
    full_spectrum_title: "Servicios de Comercio de Espectro Completo",
    full_spectrum_desc: "Optimizamos todo el proceso de la cadena de suministro, desde la primera muestra hasta la entrega final en su puerta.",
    strategic_sourcing: "Abastecimiento Estratégico",
    strategic_sourcing_desc: "Identificar y evaluar a los fabricantes más confiables en Vietnam para que coincidan con sus requisitos específicos de producto y estándares de calidad.",
    qa_card_title: "Garantía de Calidad",
    qa_card_desc: "Inspecciones en el sitio y protocolos de prueba rigurosos para garantizar que cada envío cumpla con sus expectativas antes de salir del almacén.",
    logistics_mgmt: "Logistics Management",
    logistics_mgmt_desc: "Manejo de documentación aduanera compleja y coordinación de fletes para garantizar una entrega oportuna y rentable en todo el mundo.",
    ideal_choice_title: "La Elección Ideal para el Comercio Internacional B2B",
    unmatched_network: "Red Local Incomparable",
    unmatched_network_desc: "Acceso directo a fabricantes vietnamitas de primer nivel y proveedores de materias primas.",
    total_transparency: "Transparencia Total",
    total_transparency_desc: "Seguimiento en tiempo real y comunicación clara y honesta en cada etapa del trato.",
    risk_mitigation: "Mitigación de Riesgos",
    risk_mitigation_desc: "Nos encargamos de las legalidades y el cumplimiento de los estándares para que usted pueda concentrarse en hacer crecer su negocio.",
    discuss_next_deal: "Hablemos de su Próximo Negocio Global",
    discuss_next_deal_desc: "Ya sea que busque proveedores confiables, colaboraciones comerciales o información de productos, nuestro equipo está listo para ayudarle con profesionalismo y eficiencia.",
    subject: "Asunto",
    trust_integrity_title: "Nuestro Compromiso",
    trust_integrity_quote: "La transparencia y la confianza no son solo palabras para nosotros; son los pilares sobre los que se construye cada asociación exitosa.",
    invalid_email: "Por favor, introduzca una dirección de correo electrónico válida.",
    faq_title: "Preguntas Frecuentes",
    faq_subtitle: "Encuentre respuestas a preguntas comunes sobre nuestras soluciones de importación/exportación.",
    q1: "¿Cómo garantizan la calidad del producto?",
    a1: "Realizamos inspecciones en el sitio en múltiples etapas, auditorías de fábrica y verificaciones previas al envío para garantizar que cada producto cumpla con los estándares internacionales y sus requisitos específicos.",
    q2: "¿Cuál es la cantidad mínima de pedido (MOQ) típica?",
    a2: "Las MOQ varían según la industria y el fabricante. Sin embargo, nuestra sólida red de proveedores nos permite negociar términos flexibles, a menudo facilitando pedidos iniciales más pequeños para nuevos socios internacionales.",
    q3: "¿Se encargan de toda la logística y las aduanas?",
    a3: "Sí, proporcionamos una gestión logística integral. Esto incluye documentación, coordinación de fletes y apoyo en el despacho de aduanas para garantizar una entrega fluida en su destino.",
    q4: "¿Pueden conseguir productos que no figuran en su catálogo?",
    a4: "Absolutamente. Nuestra extensa red de proveedores nos permite conseguir virtualmente cualquier producto vietnamita de alta calidad. Solo bríndenos sus especificaciones y encontraremos al proveedor ideal.",
    v5: "¿Cuáles son sus condiciones de pago estándar?",
    a5: "Generalmente trabajamos con T/T o L/C a la vista. Los términos pueden negociarse según el volumen del pedido y la relación comercial.",
    q6: "¿Cuánto tiempo tarda el proceso de abastecimiento?",
    a6: "La identificación inicial suele tardar de 5 a 7 días hábiles. Los ciclos dependen del producto, pero buscamos la máxima eficiencia.",
    q7: "¿Ofrecen servicios de OEM y marca propia?",
    a7: "Ayudamos a las marcas a fabricar en Vietnam, con soporte desde el diseño hasta el empaque final.",
    track_shipment: 'Seguimiento de su Envío',
    tracking_placeholder: 'Ingrese el número de seguimiento (ej., IDV12345)',
    track_now: 'RASTREAR AHORA',
    shipment_not_found: 'Envío no encontrado. Por favor, verifique el número.',
    status_label: 'Estado Actual',
    location_label: 'Última Ubicación',
    status_in_transit: 'En Tránsito',
    status_delivered: 'Entregado',
    status_processing: 'Procesando en Almacén',
    status_pending: 'Pendiente de Recogida',
    inquiry_type: 'Tipo de Consulta',
    general_inquiry: 'Consulta General',
    prod_sourcing: 'Abastecimiento de Productos',
    partnership: 'Asociación',
    support: 'Soporte',
    bot_error: 'Algo salió mal. Por favor, inténtalo de nuevo.',
    try_again: 'Intentar de nuevo',
    bot_error_quota: "Estamos recibiendo demasiadas solicitudes. Por favor, espere unos segundos.",
    bot_error_offline: "Parece que estás desconectado. Por favor, comprueba tu conexión.",
    bot_suggestion_contact: "Contactar Soporte",
    ai_recommended: 'Recomendaciones por IA',
    ai_insight: 'Visión de IA',
    ai_analyzing: 'Analizando sus preferencias comerciales...',
    ai_no_data: 'Comience a explorar categorías para obtener recomendaciones personalizadas.',
    team_title: 'Nuestro Equipo de Liderazgo',
    team_subtitle: 'Conozca a los expertos que vinculan la calidad vietnamita con los mercados globales.',
    ceo_role: 'Fundador y CEO',
    sourcing_role: 'Jefe de Abastecimiento Global',
    logistics_role: 'Director de Logística',
    qa_role: 'Gerente de QA y Cumplimiento'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};

const App: React.FC = () => {
  const [isDarkMode, setIsDarkMode] = useState(true);
  const [language, setLanguage] = useState<Language>('en');
  const location = useLocation();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [location.pathname]);

  useEffect(() => {
    const html = document.documentElement;
    if (isDarkMode) {
      html.classList.add('dark');
    } else {
      html.classList.remove('dark');
    }
  }, [isDarkMode]);

  useEffect(() => {
    const html = document.documentElement;
    html.setAttribute('lang', language);
    html.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
  }, [language]);

  const toggleTheme = () => setIsDarkMode(prev => !prev);
  
  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div className={`min-h-screen flex flex-col font-sans selection:bg-primary/30 ${language === 'ar' ? 'font-sans' : ''}`}>
        <Navbar isDarkMode={isDarkMode} toggleTheme={toggleTheme} />
        <main className="flex-grow">
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/products" element={<Products />} />
            <Route path="/about" element={<About />} />
            <Route path="/services" element={<Services />} />
            <Route path="/contact" element={<Contact />} />
          </Routes>
        </main>
        <Footer />
        
        {/* Floating Controls */}
        <div className={`fixed bottom-6 z-[100] flex items-center gap-3 ${language === 'ar' ? 'right-6' : 'left-6'}`}>
          <button 
            onClick={toggleTheme}
            className="w-12 h-12 rounded-full bg-white/10 dark:bg-slate-800/40 backdrop-blur-md shadow-2xl flex items-center justify-center border border-white/20 dark:border-slate-700/50 text-slate-800 dark:text-primary transition-transform hover:scale-110 active:scale-95"
            title="Toggle Theme"
          >
            <span className="material-symbols-outlined">
              {isDarkMode ? 'light_mode' : 'dark_mode'}
            </span>
          </button>
        </div>

        {/* AI Chat Bot */}
        <ChatBot />
      </div>
    </LanguageContext.Provider>
  );
};

export default App;
